dist: trusty
sudo: required

language: node_js
node_js: "stable"

addons:
  firefox: latest
  chrome: stable
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_script:
  - "apt-get update"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - npm update npm -g
  - npm install -g galenframework-cli
